config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resource :session, only: [:new, :create, :destroy] do
    collection do
      get 'login'  => 'sessions#login', as: :login
      post 'sign_in' => 'sessions#sign_in', as: :sign_in
    end
  end
  post 'likes/:id' => 'likes#add_like_to_database', as: :add_like
  post 'dislikes/:id' => 'dislikes#add_unlike_to_database', as: :add_unlike

end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :disinterest, :class_name => "User"
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :likes
  has_many :dislikes
  has_many :interests, through: :likes
  has_many :disinterests, through: :dislikes

  validates :username, presence: true

  def find_interest
    interested_gender = self.interested_gender
    preferred_age = self.preferred_age
    preferred_age_range = preferred_age..(preferred_age+8)
    # Find matches based on the user's input
    interests = User.where({interested_gender: interested_gender,
                          preferred_age: preferred_age_range})
                   .where.not(id: self.id)
    interested_users = []
    interests.map do |interest|
      # check if the user has "Yes" or "No" the person yet
      if !(self.interests.include?(interest) || self.disinterests.include?(interest))
        # maximize matches
        if interest.interests.include?(self)
          if rand > 0.4
            interested_users.unshift(interest)
          else
            interested_users.push(interest)
          end
        else
          interested_users.push(interest)
        end
      end
    end
    # return one to the user
    interested_users[0] if interested_users != nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def confirm_logged_in
    unless session[:current_user_id]
      flash[:notice] = "Please log in or sign up."
      redirect_to new_session_path
      return false # halts the before_action
    else
      return true
    end
  end

end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController

  def add_unlike_to_database
    Dislike.create({user_id: session[:current_user_id], disinterest_id: params[:id]})
    redirect_to root_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def add_like_to_database
    Like.create({user_id: session[:current_user_id], interest_id: params[:id]})
    user = User.find(session[:current_user_id])
    interest_likes = User.find(params[:id]).interests
    if interest_likes.include?(user)
      flash[:message] = "It is a match"
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render "new"
  end

  def login
    # login form
  end

  def sign_in
    @user = User.where(:username => params[:username])[0]
    if !@user.nil?
      session[:current_user_id] = @user.id
      session[:username] = @user.username
      redirect_to root_path
    else
      redirect_to new_session_path
    end
    #sign_in
  end

  def create
    if params[:user].present?
      user = User.where(:username => params[:user][:username])
      if user.empty?
        @user = User.new(user_params)
        if @user.save
          session[:current_user_id] = @user.id
          session[:username] = @user.username
          redirect_to root_path
        else
          redirect_to new_session_path
        end
      else
        flash[:notice] = "Someone has taken this Username"
        redirect_to new_session_path
        # authorized_user = found_user.authenticate(params[:password])
      end
    end
  end

  def destroy
    # mark user as logged out
    session[:current_user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to(:action => "login")
  end

  private

    def user_params
      params.require(:user).permit(:username, :gender, :interested_gender, :age, :preferred_age)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :confirm_logged_in

  def index
    user = User.find(session[:current_user_id])
    @interest = user.find_interest
    if @interest == nil
      flash[:message] = "No more Matches"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<a href="<%= matches_path %>">Your matches</a>
<p> Interests </p>

<div class="interestsDiv">
  <% if @interest != nil %>
    <label> Username: </label>
    <label> <%= @interest.username %> </label>
    <br>
    <label> Age: <label>
    <label> <%= @interest.age %> </label>
    <br>
    <label> Gender: </label>
    <label> <%= @interest.gender %> </label>

  <%= button_to "Yes", add_like_path(@interest.id)%>
  <%= button_to "No", add_unlike_path(@interest.id) %>
  <% end %>
</div>

<div id="flash">
  <h2 id="flashMessage"><%= flash[:message] %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TinyTinderApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:current_user_id] != nil %>
  <div>
    <label> Welcome <%= session[:username] %></label>
    <label><%= link_to "Logout", session_path, method: :delete, id: "logout" %></label>
  </div>
<% end %>

  <%= yield %>

</body>
</html>

app/views/users/index.html.erb
<p> Interests </p>

<div class="interestsDiv">
  <% if @interest != nil %>
    <label> Username: </label>
    <label> <%= @interest.username %> </label>
    <br>
    <label> Age: <label>
    <label> <%= @interest.age %> </label>
    <br>
    <label> Gender: </label>
    <label> <%= @interest.gender %> </label>

  <%= button_to "Yes", add_like_path(@interest.id)%>
  <%= button_to "No", add_unlike_path(@interest.id) %>
  <% end %>
</div>

<div id="flash">
  <h2 id="flashMessage"><%= flash[:message] %></h2>
</div>